// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/dashboard";
  };
  "routes/auth/login-page.tsx": {
    id: "routes/auth/login-page";
    page: "/login";
  };
  "routes/auth/logout.ts": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "./components/layout/dashboard-layout.tsx": {
    id: "components/layout/dashboard-layout";
    page: "/dashboard";
  };
  "./routes/index/home.tsx": {
    id: "routes/index/home";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/login-page": typeof import("./app/routes/auth/login-page.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.ts");
  "components/layout/dashboard-layout": typeof import("./app/./components/layout/dashboard-layout.tsx");
  "routes/index/home": typeof import("./app/./routes/index/home.tsx");
};